In [9]:
import numpy as np

In [10]:
array1 = np.array([[10, 8], [3, 5]])

In [11]:
array1

array([[10,  8],
       [ 3,  5]])

In [12]:
#1 計算反矩陣
inv = np.linalg.inv(array1)

In [13]:
#1 與原矩陣相乘後為單位矩陣
np.dot(array1,inv)

array([[1., 0.],
       [0., 1.]])

In [14]:
value,vector = np.linalg.eig(array1)

In [15]:
#特徵值
value

array([13.,  2.])

In [16]:
#特徵向量
vector

array([[ 0.93632918, -0.70710678],
       [ 0.35112344,  0.70710678]])

In [17]:
u,s,vh = np.linalg.svd(array1)

In [18]:
u

array([[-0.91663818, -0.39971796],
       [-0.39971796,  0.91663818]])

In [19]:
s

array([13.94721714,  1.86417116])

In [20]:
vh

array([[-0.74319741, -0.6690722 ],
       [-0.6690722 ,  0.74319741]])