In [1]:
import numpy as np

In [2]:
#. 將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])

In [4]:
#將array1寫進'array1.npy'
#with open....as 將檔案開啟及自動關閉
with open('array1.npy','wb') as a:
    np.save(a,array1)

In [5]:
#將array2寫進'array2.npy'

with open('array2.npy','wb') as b:
    np.save(b,array2)

In [6]:
np.load('array1.npy')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [7]:
np.load('array2.npy')

array([2, 3, 5])

In [8]:
#savez版
with open('mix.npy','wb') as mix:
    np.savez(mix,array1 = array1,array2 = array2)

In [9]:
np.load('mix.npy')

In [11]:
print(np.load('mix.npy')['array1'])
print(np.load('mix.npy')['array2'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]


In [12]:
#save版
with open('mix1.npy','wb') as mix1:
    np.save(mix1,array1)
    np.save(mix1,array2)


In [18]:
with open('mix1.npy','rb') as mix1:
    a = np.load(mix1)
    b = np.load(mix1)
    
print(a)
print(b)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
