In [40]:
import numpy as np

english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,55,60])
chinese_score = np.array([65,90,82,72,66,77])

In [86]:
a = np.greater(english_score,math_score)
b = np.where(a == True)#只要True的學生就代表英文比數學高
print(a)
print(b)
print(b[0])
print(len(b[0]))




[False  True  True False False  True]
(array([1, 2, 5], dtype=int64),)
[1 2 5]
3


In [33]:
ch_math_greater = np.greater(chinese_score,math_score)
ch_eng_greater = np.greater(chinese_score,english_score)

print(np.logical_and(ch_math_greater,ch_eng_greater))
#print(np.logical_and(ch_math_greater,ch_eng_greater).any())

[ True  True  True  True  True  True]
True


array([ True,  True,  True,  True,  True,  True])